help: |-
  {{name}} Is an AI Native software, for individual/group intelligent management.
  ------------------------------
  Feats：
    1. Parser: LLM powered AI Parser
    2. Chatter: LLM powered AI Chatter
    3. Todo: Your Personal TODO
    4. Reminder: Your Personal Reminder (todo)
    5. Love: An Emotional Hive (todo)
    0. System: Preference Relative
  ------------------------------
  Basic Commands：
    status: (show preference)
    help: (show usage)

status: |-
  Basic:
    alive-time: {{aliveTime}}
  ------------------------------
  Preference:
    model: {{preference.model}}
    backend: {{preference.backend}}
    chat-enabled: {{{preference.chatEnabled}}}
    parser-enabled: {{{preference.parserEnabled}}}
    max-output-lines: {{{preference.maxOutputLines}}}
