help: |-
  {{name}} Is an AI Native software, for individual/group intelligent management.
  ------------------------------
  Feats：
    1. Chatter: LLM powered AI Chatter
    2. Parser: LLM powered AI Parser
    3. Todo: Task Management
  ------------------------------
  Basic Commands：
    /help [FEAT]: (show usage of specific feature)
    /status: (show preference)
    /set-lang zh: (切换为中文)
  ------------------------------

status: |-
  Basic:
    alive-time: {{aliveTime}}
  ------------------------------
  Preference:
    model: {{preference.model}}
    backend: {{preference.backend}}
    chat-enabled: {{{preference.chatEnabled}}}
    parser-enabled: {{{preference.parserEnabled}}}
