name: Okawa Plus

help: |-
  {{name}} Is an AI Native software, for individual/group intelligent management.
  ------------------------------
  Feats：
    1. Parser: AI Parser for anything
    2. Chatter: AI Chatter knows anything
    3. Lover: Your Emotional Hive (todo)
    3. Todo: Your Personal Task Manager (with Reminder)
    0. System: Preference Relative
  ------------------------------
  Basic Commands：
    status: (show preference)
    help: (show usage)

status: |-
  Basic:
    name: {{{name}}}
    version: {{{version}}}
    alive-time: {{aliveTime}}
  ------------------------------
  Preference(Conv|User):
    model: {{convPreference.model}} | {{userPreference.model}}
    backend: {{convPreference.backend}} | {{userPreference.backend}}
    chatter enabled: {{{convPreference.chatEnabled}}} | {{{userPreference.chatEnabled}}}
    parser enabled: {{{convPreference.parserEnabled}}} | {{{userPreference.parserEnabled}}}
    max output lines: {{{convPreference.maxOutputLines}}} | {{{userPreference.maxOutputLines}}}
    command style: {{{convPreference.commandStyle}}} | {{{userPreference.commandStyle}}}
