name: Okawa Plus

help: |-
  {{name}} Is an AI Native software, for individual/group intelligent management.
  ------------------------------
  Feats：
    1. Parser: AI Parser for anything
    2. Chatter: AI Chatter knows anything
    3. Lover: Your Emotional Hive (todo)
    3. Todo: Your Personal Task Manager (with Reminder)
    0. System: Preference Relative
  ------------------------------
  Basic Commands：
    status: (show preference)
    help: (show usage)

status: |-
  Basic:
    name: {{{name}}}
    version: {{{version}}}
    alive-time: {{aliveTime}}
  ------------------------------
  Preference:
    model: {{preference.model}}
    backend: {{preference.backend}}
    chat-enabled: {{{preference.chatEnabled}}}
    parser-enabled: {{{preference.parserEnabled}}}
    max-output-lines: {{{preference.maxOutputLines}}}
    command-style: {{{preference.commandStyle}}}
