help: |-
  {{name}} Is an AI Native software, for individual/group intelligent management.
  ------------------------------
  Feats：
    1. Parser: LLM powered AI Parser
    2. Chatter: LLM powered AI Chatter
    3. Todo: Task Management
    0. System: Preference Relative
  ------------------------------
  Basic Commands：
    /help [FEAT]: (show usage of specific feature)
    /status: (show preference)
  ------------------------------

status: |-
  Basic:
    alive-time: {{aliveTime}}
  ------------------------------
  Preference:
    model: {{preference.model}}
    backend: {{preference.backend}}
    chat-enabled: {{{preference.chatEnabled}}}
    parser-enabled: {{{preference.parserEnabled}}}
