name: Okawa Plus

help: |-
  {{name}} Is an AI Native software, for individual/group intelligent management.
  ------------------------------
  Feats：
    1. Parser: AI Parser for anything
    2. Chatter: AI Chatter knows anything
    3. Lover: Your Emotional Hive (todo)
    3. Todo: Your Personal Task Manager (with Reminder)
    0. System: Preference Relative
  ------------------------------
  Basic Commands：
    status: (show preference)
    help: (show usage)

status: |-
  Basic:
    name: {{{name}}}
    version: {{{version}}}
    alive-time: {{aliveTime}}
  ------------------------------
  ConvPreference:
    model: {{convPreference.model}}
    backend: {{convPreference.backend}}
    chatter enabled: {{{convPreference.chatEnabled}}}
    parser enabled: {{{convPreference.parserEnabled}}}
    max output lines: {{{convPreference.maxOutputLines}}}
    command style: {{{convPreference.commandStyle}}}
  ------------------------------
  UserPreference:
    model: {{userPreference.model}}
    backend: {{userPreference.backend}}
    chatter enabled: {{{userPreference.chatEnabled}}}
    parser enabled: {{{userPreference.parserEnabled}}}
    max output lines: {{{userPreference.maxOutputLines}}}
    command style: {{{userPreference.commandStyle}}}
