name: Okawa Plus

help: |-
  {{name}} Is an AI Native software, for individual/group intelligent management.
  ------------------------------
  Feats：
    1. Parser: AI Parser for anything
    2. Chatter: AI Chatter knows anything
    3. Lover: Your Emotional Hive (todo)
    3. Todo: Your Personal Task Manager (with Reminder)
    0. System: Preference Relative
  ------------------------------
  Basic Commands：
    status: (show preference)
    help: (show usage)

status: |-
  Basic:
    name: {{{name}}}
    version: {{{version}}}
    alive-time: {{aliveTime}}
  ------------------------------
  Preference(Conv|User):
    model: {{convPreference.fetch.detail.summary.model}} | {{userPreference.fetch.detail.summary.model}}
    chatter enabled: {{{convPreference.chatterEnabled}}} | {{{userPreference.chatterEnabled}}}
    parser enabled: {{{convPreference.parserEnabled}}} | {{{userPreference.parserEnabled}}}
    backend: {{convPreference.fetch.detail.request.backendType}} | {{userPreference.fetch.detail.request.backendType}}
    max output lines: {{{convPreference.maxOutputLines}}} | {{{userPreference.maxOutputLines}}}
    command style: {{{convPreference.commandStyle}}} | {{{userPreference.commandStyle}}}
