# ---------------
# 通用
# ---------------
yarnPath: .yarn/releases/yarn-4.4.0.cjs

nodeLinker: node-modules

setEnv:
#  jq 很难下载，在 mac 上用 brew，在 ubuntu 上用 apt 即可
#  nodejs 的 jq 似乎有问题
  NODE_JQ_SKIP_INSTALL_BINARY: "true"

# ---------------
# 代理相关
# ---------------
httpProxy: "http://localhost:7890"

httpsProxy: "http://localhost:7890"

# 这个巨大，在服务器端还是很需要使用代理的
electronMirror: "https://npmmirror.com/mirrors/electron/"
