# ---------------
# 通用
# ---------------
yarnPath: .yarn/releases/yarn-4.4.0.cjs

nodeLinker: node-modules

injectEnvironmentFiles:
  - .env

# ---------------
# 代理相关
# ---------------
httpProxy: "http://localhost:7890"

httpsProxy: "http://localhost:7890"
