help: |-
  {{name}}是一款 AI Native 的智能助手，可用于个人、群组智能管理、协同。
  ------------------------------
  目前支持以下子功能：
  - A1: 话题级别的 AI 聊天
    /开启AI聊天
    /结束AI聊天
    /查询历史话题
    /继续话题 [标题]
    /开启新话题 [标题]
  
  - A2: 信息总结（已支持：订阅号文章……）
    /开启万能解析
    /结束万能解析
  
  - A3: 任务管理
    /查询任务
    /添加任务 [标题]
    /标记任务 [标题] [状态]
  ------------------------------
  基本命令列表：
  /状态
  /查询模型列表
  /设置模型 [类型]
  /帮助
  /帮助 [子功能名称]
  ------------------------------
  /set-lang en: switch to english

status: |-
  Basic:
    alive-time: {{aliveTime}}
  ------------------------------
  Preference:
    model: {{preference.model}}
    backend: {{preference.backend}}
    uni-chatter-enabled: {{{conv.uniChatterEnabled}}}
    uni-parser-enabled: {{{conv.uniParserEnabled}}}
