help: |-
  {{name}} Is an AI Native software, for individual, group intelligent management, collaboration.
  ------------------------------
  Feats：
  - Chat: Chat with AI
  - Parser: Info Summarization
  - Todo: Task Management
  ------------------------------
  Basic Commands：
  /
  /status
  /help [FEAT]
  ------------------------------
  切换为中文，请发送：/设置语言 中文

status: |-
  Basic:
    alive-time: {{aliveTime}}
  ------------------------------
  Preference:
    model: {{preference.model}}
    backend: {{preference.backend}}
    chat-enabled: {{{preference.chatEnabled}}}
    parser-enabled: {{{preference.parserEnabled}}}
