basic: |-
  +----------------------------+
  {{title}}
  ------------------------------
  {{content}}
  ------------------------------
  {{footer}}
  +----------------------------+

help: |-
  {{name}}是一款 AI Native 的智能助手，可用于个人、群组智能管理、协同。
  ------------------------------
  目前支持以下子功能：
  - A1: 话题级别的 AI 聊天
  - A2: 信息总结（已支持：订阅号文章……）
  - ……
  ------------------------------
  命令列表：
  /: 帮助
  /ding: 心跳检测
  /status: 查询状态
  /list-models: 查询AI模型列表
  /set-model: 设置AI模型
  /start-chat: 开始AI聊天
  /stop-chat: 结束AI聊天
  /list-topics: 查询历史话题
  /set-topic [N]: 继续第N个话题
  /new-topic [TITLE]: 开启新话题
  /help [FEAT]: 查询子功能帮助

status: |-
  Basic:
    alive-time: {{aliveTime}}
  ------------------------------
  Preference:
    model: {{preference.model}}
    backend: {{preference.backend}}
    handlers: {{{prettyHandlers}}}
  ------------------------------
  Conv:
    uni-chatter-enabled: {{{conv.uniChatterEnabled}}}
    uni-parser-enabled: {{{conv.uniParserEnabled}}}
